// Shared presentation copy. Portfolio facts remain in site-data and project-service.
export const homepageContent = {
  hero: {
    title: "Full-stack software engineer building production web, API, and desktop products.",
    intro: "I'm Ayan Dutta, a Kolkata-based Software Engineer at YoForex. I work across React and TypeScript interfaces, Go and FastAPI services, PostgreSQL data, and Electron desktop workflows.",
    projectsLabel: "View Projects",
    cvLabel: "Download CV",
    contactLabel: "Contact Me",
    scene: "https://prod.spline.design/PyzDhpQ9E5f1E3MT/scene.splinecode",
  },
  projects: {
    eyebrow: "Selected Work",
    title: "Proof of work, not just a list of technologies.",
    allTitle: "Projects across product, platform, and systems work.",
    description: "Each project connects the implementation choices to a real workflow, technical challenge, or product outcome.",
    allProjectsLabel: "View all projects",
    caseStudyLabel: "Read case study",
    conceptLabel: "Concept visual",
    featuredLabel: "Featured project",
  },
  skills: {
    eyebrow: "Capabilities",
    title: "A full-stack toolkit organized around shipping useful products.",
    description: "Core technologies, delivery practices, and evidence from the work behind this portfolio.",
  },
  experience: {
    eyebrow: "Experience",
    title: "Production experience backed by engineering foundations.",
    description: "A concise timeline of production delivery, professional experience, and technical education.",
  },
  workflow: {
    eyebrow: "AI Workflow",
    note: "AI can accelerate a first implementation; code ownership, review, testing, and refinement make it ready to ship.",
  },
  about: {
    eyebrow: "About",
    title: "Engineering fundamentals with a product builder’s mindset.",
    description: "A practical path from electronics and systems thinking to production-minded software development.",
    approachLabel: "My approach",
    approachTitle: "Build clearly. Validate carefully. Keep improving.",
    detail: "My electronics background adds systems thinking to software work: understanding constraints, tracing behavior, and turning technical decisions into dependable user experiences.",
    strengthsLabel: "What I bring",
    locationSuffix: " · Kolkata",
  },
  faq: {
    eyebrow: "Recruiter FAQ",
    title: "Quick answers for hiring teams.",
    description: "Role fit, production experience, technical strengths, availability, and the fastest way to get in touch.",
  },
  contact: {
    eyebrow: "Let’s Work Together",
    title: "Looking for a developer who can move from idea to implementation?",
    description: "I’m open to full-stack, frontend, and software engineering opportunities where practical execution matters.",
    pitchTitle: "Ready to discuss the right product engineering role.",
    pitchIntro: "I'm currently a Software Engineer at YoForex and open to discussing ",
    pitchOutro: " roles. I bring production full-stack experience across React, Go, FastAPI, PostgreSQL, and Electron.",
    emailLabel: "Email me about a role",
    resumeLabel: "View resume",
    responseSuffix: " · Email or LinkedIn both work.",
    copyPrompt: "Prefer to paste it?",
    emailDetailLabel: "Email",
    linkedInLabel: "LinkedIn",
    linkedInDescription: "Professional profile",
    gitHubLabel: "GitHub",
    gitHubDescription: "Code and repositories",
    resumeDetailLabel: "Resume",
    downloadLabel: "Download PDF",
    locationLabel: "Based in",
  },
};
